version: '3'

services:
  servidorweb:
    #image: webdevops/php-apache
    build: .
    container_name: servidorweb
    volumes:
      - ./app:/app
    ports:
      - 86:80

  servidorbd:
    image: mariadb:10.7.1
    container_name: servidordb
    environment:
      - MYSQL_ROOT_PASSWORD=anaconda/26/mangosta
    volumes:
      - ./db:/var/lib/mysql
      - ./db_config:/etc/mysql/conf.d
    ports:
      - 3340:3306
     # docker-compose up -d servidorweb
